### ISSUE TITLE
Debugger: jsonDocs.events entry may be undefined

### ISSUE THREAD

**Issue by gabrielschulhof** [arschmitz/jquery-mobile-event-debugger#3]
At https://github.com/arschmitz/jquery-mobile-event-debugger/blob/v0.0.1/debugger.js#L116, `jsonDocs.events[ name ]` may be undefined, causing $.each() to throw an exception.

**Comment by arschmitz** [comment]
if there is an event without a name thats an issue in the api docs

**Comment by gabrielschulhof** [comment]
The value of `name` that throws an error is `"page"`.

**Comment by gabrielschulhof** [comment]
`find entries -type f | xargs grep -niH '<entry' | grep 'type=.event.' | grep -v 'name='` returns empty, so all our events /should/ have names.

**Comment by arschmitz** [comment]
can you try this on master i cannot reporduce

**Comment by gabrielschulhof** [comment]
How do you mean "try this on master"? I'm trying on branch "page-events-demo". Do you mean that I should rebase page-events-demo onto master?

**Comment by gabrielschulhof** [comment]
Oh, I guess you mean I should try with the version of debugger.js from master. I'll try that.

**Comment by arschmitz** [comment]
Turns out this was an issue with the local install of php not fetching the docs xml closing.
