### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by everstrivin** [arschmitz/jquery-mobile-event-debugger#4]
I can't locate anywhere where someone shows how to use it.

I included the jquery.mobile.event.debugger.js then as instructed I immediately did $.mobile.eventlogger([showAlert]);

Didn't work, so now hoping for some help.  Just a sample standard usage example showing typical placements for the above mentioned code snippets would be great.

Thanks

**Comment by ppetree** [comment]
Did you ever find any examples?

**Comment by consciousimages** [comment]
As per: [https://demos.jquerymobile.com/1.5.0-rc1/page-events/logevents.html](url)
Something like this: 

`
		$.mobile.eventLogger({
			deprecated: true,
			events: {
				page: true
			},
			widgets: {
				page: true,
				pagecontainer: true
			}
		});
	`

**Comment by ppetree** [comment]
Ha! Thanks for the flashback! 

I wrote this several (many) years ago and recently did a rewrite and turned it into a git.
[https://github.com/ppetree/cordova-console-log](https://github.com/ppetree/cordova-console-log)
